[build]
  # Base directory is the frontend Angular project
  base = "FSD-Participation/frontend"
  
  # Angular build command with cleanup
  command = "rm -f package-lock.json && npm install && npm run build:prod"
  
  # Angular output directory (dist/[project-name])
  publish = "dist/social-media-app/browser"

# Environment variables
[build.environment]
  NODE_VERSION = "18" # Using LTS version for better compatibility

# Handle Angular routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 