services:
  - type: web
    name: participation-backend
    env: docker
    region: oregon # Choose a region closest to your users
    plan: free
    dockerfilePath: ./FSD-Participation/backend/Dockerfile
    dockerContext: ./FSD-Participation/backend
    buildCommand: ./mvnw clean package -DskipTests
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cvqc1ore5dus73f6ncc0-a.oregon-postgres.render.com:5432/fsdproject_9hsk
      - key: SPRING_DATASOURCE_USERNAME
        value: fsdproject_9hsk_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: c14NMNajHfYVbvOAl3nRee01PyK5svrB
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health # Remove if you don't have Spring Actuator
    autoDeploy: true
